version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_voting_agenda
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: voting_agenda
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network
    restart: unless-stopped

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
